#!/bin/bash
#install chromium brower and flash plugin
echo "install chromium brower and flash plugin"
sudo apt-get install chromium-browser -y
sudo apt-get install pepperflashplugin-nonfree -y
sudo update-pepperflashplugin-nonfree --install 
