#!/bin/bash
#install firefox flash plugin
mkdir fireboxflash
cd fireboxflash
axel https://fpdownload.adobe.com/get/flashplayer/pdc/11.2.202.508/install_flash_player_11_linux.x86_64.tar.gz
tar zxvf install_flash_player_11_linux.x86_64.tar.gz 
sudo cp libflashplayer.so /usr/lib/mozilla/plugins
sudo cp -r usr/* /usr  
cd ..
sudo rm -r fireboxflash
sudo rm install_flash_player_11_linux.x86_64.tar.gz 

