#!/bin/bash
# 14.04 -> indigo or jade
# 14.10 15.04 -> jade
# create by Cloud9

function InstallRos()
{
	sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'

	sudo apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv-key 0xB01FA116

	sudo apt-get update

	sudo apt-get install "ros-$RosVersion-desktop-full" -y

	sudo rosdep init
	rosdep update

	echo "source /opt/ros/$RosVersion/setup.bash" >> ~/.bashrc
	source ~/.bashrc

	sudo apt-get install python-rosinstall -y
}
function InstallIndigo ()
{
	sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'

	sudo apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv-key 0xB01FA116

	sudo apt-get update

	sudo apt-get install ros-indigo-desktop-full -y

	sudo rosdep init
	rosdep update

	echo "source /opt/ros/indigo/setup.bash" >> ~/.bashrc
	source ~/.bashrc

	sudo apt-get install python-rosinstall
}

function InstallJade ()
{
	sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'

	sudo apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv-key 0xB01FA116

	sudo apt-get update

	sudo apt-get install ros-jade-desktop-full -y

	sudo rosdep init
	rosdep update

	echo "source /opt/ros/jade/setup.bash" >> ~/.bashrc
	source ~/.bashrc

	sudo apt-get install python-rosinstall
}


# check os version
if cat /etc/lsb-release | grep -i "\b 14.04 \b" >/dev/null 2>&1
	then
	OsVersion="14.04"
	echo "u Os Version is $OsVersion"
elif cat /etc/lsb-release | grep -i "\b 14.10\b" >/dev/null 2>&1
	then
	OsVersion="14.10"
	echo "u Os Version is $OsVersion"
elif cat /etc/lsb-release | grep -i "\b 15.04\b" >/dev/null 2>&1
	then
	OsVersion="15.04"
	echo "u Os Version is $OsVersion"
else
	OsVersion=OsVersion=$(cat /etc/issue)
	echo "u Os Version is $OsVersion"
	echo "i suggest u to choose your os to Ubuntu 14.04,14.10 or 15.04"
	return 1
fi



# choose ros version
if [ "$OsVersion" == "14.04" ]
	then
	echo -n "Your os version is $OsVersion,please input Jade or Indigo u want to install:"
	read RosVersion
	RosVersion=$(echo "$RosVersion" | tr A-Z a-z);
	echo "Your choose is $RosVersion"
else
	RosVersion="jade"
	echo "Your choose is $RosVersion"
fi

# check ros version
if [ "$RosVersion" == "indigo" ]
	then
	echo "Your choose is $RosVersion"
elif [ "$RosVersion" == "jade" ]
	then
	echo "Your choose is $RosVersion"
else
	echo "Your choose is $RosVersion is not availavle"
	return 1
fi

# install Ros
InstallRos
