#!/bin/bash
echo "# deb cdrom:[Ubuntu 14.10 _Utopic Unicorn_ - Release amd64 (20141022.1)]/ utopic main restricted

# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
# newer versions of the distribution.
deb http://mirrors.aliyun.com/ubuntu/ utopic main restricted
deb-src http://mirrors.aliyun.com/ubuntu/ utopic main restricted

## Major bug fix updates produced after the final release of the
## distribution.
deb http://mirrors.aliyun.com/ubuntu/ utopic-updates main restricted
deb-src http://mirrors.aliyun.com/ubuntu/ utopic-updates main restricted

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team. Also, please note that software in universe WILL NOT receive any
## review or updates from the Ubuntu security team.
deb http://mirrors.aliyun.com/ubuntu/ utopic universe
deb-src http://mirrors.aliyun.com/ubuntu/ utopic universe
deb http://mirrors.aliyun.com/ubuntu/ utopic-updates universe
deb-src http://mirrors.aliyun.com/ubuntu/ utopic-updates universe

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu 
## team, and may not be under a free licence. Please satisfy yourself as to 
## your rights to use the software. Also, please note that software in 
## multiverse WILL NOT receive any review or updates from the Ubuntu
## security team.
deb http://mirrors.aliyun.com/ubuntu/ utopic multiverse
deb-src http://mirrors.aliyun.com/ubuntu/ utopic multiverse
deb http://mirrors.aliyun.com/ubuntu/ utopic-updates multiverse
deb-src http://mirrors.aliyun.com/ubuntu/ utopic-updates multiverse

## N.B. software from this repository may not have been tested as
## extensively as that contained in the main release, although it includes
## newer versions of some applications which may provide useful features.
## Also, please note that software in backports WILL NOT receive any review
## or updates from the Ubuntu security team.
deb http://mirrors.aliyun.com/ubuntu/ utopic-backports main restricted universe multiverse
deb-src http://mirrors.aliyun.com/ubuntu/ utopic-backports main restricted universe multiverse

deb http://mirrors.aliyun.com/ubuntu/ utopic-security main restricted
deb-src http://mirrors.aliyun.com/ubuntu/ utopic-security main restricted
deb http://mirrors.aliyun.com/ubuntu/ utopic-security universe
deb-src http://mirrors.aliyun.com/ubuntu/ utopic-security universe
deb http://mirrors.aliyun.com/ubuntu/ utopic-security multiverse
deb-src http://mirrors.aliyun.com/ubuntu/ utopic-security multiverse

## Uncomment the following two lines to add software from Canonical's
## 'partner' repository.
## This software is not part of Ubuntu, but is offered by Canonical and the
## respective vendors as a service to Ubuntu users.
# deb http://archive.canonical.com/ubuntu utopic partner
# deb-src http://archive.canonical.com/ubuntu utopic partner

## This software is not part of Ubuntu, but is offered by third-party
## developers who want to ship their latest software.
deb http://extras.ubuntu.com/ubuntu utopic main
deb-src http://extras.ubuntu.com/ubuntu utopic main" |sudo tee /etc/apt/sources.list

sudo apt-get update
sudo apt-get install gcc
sudo apt-get install g++
sudo apt-get install git
sudo apt-get install cutecom
sudo apt-get install filezilla
sudo apt-get install vim
sudo apt-get install terminator

#install chromium brower and flash plugin
echo "install chromium brower and flash plugin"
sudo apt-get install chromium-browser -y
sudo apt-get install pepperflashplugin-nonfree -y
sudo update-pepperflashplugin-nonfree --install 

#install sublime
echo "install sublime 2"
sudo apt-get install axel
axel http://c758482.r82.cf2.rackcdn.com/Sublime\ Text\ 2.0.2\ x64.tar.bz2
tar jxvf Sublime\ Text\ 2.0.2\ x64.tar.bz2
sudo rm Sublime\ Text\ 2.0.2\ x64.tar.bz2
sudo mv Sublime\ Text\ 2 /usr/lib/SublimeText2
sudo ln -s /usr/lib/SublimeText2/sublime_text /usr/bin/sublime
sudo echo "[Desktop Entry]
Version=1.0
Name=Sublime Text 2
GenericName=Text Editor
Exec=sublime
Terminal=false
Icon=/usr/lib/SublimeText2/Icon/48x48/sublime_text.png
Type=Application
Categories=testEditor:IDE:Development
X-Ayatana-Desktop-Shortcuts=NewWindow
[NewWindow Shortcut Group]
Name=New Window
Exec=sublime -n
TargetEnviroment=Unity" > sublime.desktop
sudo mv sublime.desktop /usr/share/applications/sublime.desktop

#openssh
sudo apt-get install openssh-server -y
sudo sed -i 's/without-password/yes/g' /etc/ssh/sshd_config





    




